routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return redirect('login');
});

Route::any('/webhook', 'WebhookController@index');

Auth::routes();

Route::middleware('auth')->resource('projects', 'ProjectsController');

app/Log.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Log extends Model
{
    protected $guarded = [];

    protected $dates = [
        'created_at',
        'updated_at'
    ];

    public function project()
    {
        return $this->belongsTo(Project::class);
    }
}

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    protected $guarded = [];

    protected $appends = ['status_name'];

    protected $status_codename = [
        0 => 'Inactive',
        1 => 'Active',
    ];

    protected $dates = [
        'created_at',
        'updated_at'
    ];

    public function getStatus($status)
    {
        return $this->status_codename[$status];
    }

    public function getStatusNameAttribute()
    {
        return $this->getStatus($this->status);
    }

    public function getLastLogAttribute()
    {
        return $this->logs->sortByDesc('updated_at')->first();
    }

    public function logs()
    {
        return $this->hasMany(Log::class)->orderBy('updated_at', 'desc');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;
use DB;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
        return view('projects.index')->with([
            'projects' => $projects
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('projects.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            $project = new Project();
            $project->fill($request->all());
            $project->save();
            DB::commit();
            return redirect()->route('projects.index');
        } catch (Exception $e) {

            DB::rollback();
            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        $project->load('logs');
        return view('projects.show')->with([
            'project' => $project
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        return view('projects.form')->with([
            'project' => $project
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        DB::beginTransaction();
        try {
            $project->fill($request->all());
            $project->save();
            DB::commit();
            return redirect()->route('projects.index');
        } catch (Exception $e) {

            DB::rollback();
            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }
}

app/Http/Controllers/WebhookController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use Illuminate\Http\Request;
use DB;
use App\Jobs\DeployProject;

class WebhookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hook_data = collect(json_decode(file_get_contents("php://input")));
        $log = new \App\Log();

        $projects = \App\Project::where('namespace', ($hook_data['project'])->path_with_namespace)->get();
        foreach ($projects as $project) {
            if ($project === null) {
                $log->status = "0";
                $log->content = "Repository Not Found";
                $project->logs()->save($log);
                return response("Failed", 200);
            }

            dispatch((new DeployProject($project))->delay(\Carbon\Carbon::now()->addSeconds(5)));
        }

        return response("Success", 200);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@yield('title', "Dashboard")</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/main.css') }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    @stack('css')
</head>
<body>
    @if (auth()->check())
        <nav>
            <div class="nav-wrapper indigo">
                <a href="{{ route('projects.index') }}" class="brand-logo" style="padding-left: 20px">Deployer</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    {!! Form::open(['url' => route('logout'), 'id' => 'form-logout']) !!}
                        <li><a onclick="$('#form-logout').submit()" type="submit">Logout</a></li>
                    {!! Form::close() !!}
                </ul>
            </div>
        </nav>
    @endif

    @yield('main-content')

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/js/materialize.min.js"></script>
    @stack('js')
</body>
</html>

resources/views/projects/form.blade.php
@extends('layouts.dashboard')

@push('css')
<style>
    body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
    }

    main {
        flex: 1 0 auto;
    }

    body {
        background: #fff;
    }

    .input-field input[type=date]:focus + label,
    .input-field input[type=text]:focus + label,
    .input-field input[type=email]:focus + label,
    .input-field input[type=password]:focus + label {
        color: #e91e63;
    }

    .input-field input[type=date]:focus,
    .input-field input[type=text]:focus,
    .input-field input[type=email]:focus,
    .input-field input[type=password]:focus {
        border-bottom: 2px solid #e91e63;
        box-shadow: none;
    }
    input:-webkit-autofill {
        -webkit-box-shadow: 0 0 0 30px #fafafa  inset !important;
    }
</style>
@endpush

@section('main-content')
@php
    $isEdit = isset($project);
    if ($isEdit) {
        $formUrl = route('projects.update', $project->id);
        $formMethod = "PATCH";
    } else {
        $formUrl = route('projects.store');
        $formMethod = "POST";
    }
@endphp
<body style="background-color: #eee">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="hidden toastMessage" data-content="{{ $error }}"></div>
        @endforeach
    @endif
    <div class="section"></div>
    <main>
        <center>
            <div class="section">
                <h4>{{ $isEdit ? "EDIT" : "CREATE" }} PROJECT</h4>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col s12 m10 l8 offset-m4 offset-l2">
                        <div class="z-depth-1 grey lighten-5 row" style="padding: 32px 48px 0px 48px;">
                            {!! Form::model($project ?? null, ['url' => $formUrl, 'class' => 'col s12', 'method' => $formMethod]) !!}
                                <div class='row'>
                                    {{ Form::mzText('name', 'Project Name') }}
                                </div>
                                <div class='row'>
                                    {{ Form::mzText('branch', 'Branch') }}
                                </div>
                                <div class='row'>
                                    {{ Form::mzText('namespace', 'Project Namespace (user/project)') }}
                                </div>
                                <div class='row'>
                                    {{ Form::mzText('path', 'Path') }}
                                </div>
                                <div class='row'>
                                    {{ Form::mzSelect('status', 'Status', ['0' => 'Inactive', '1' => 'Active']) }}
                                </div>
                                <div class='row'>
                                    {{ Form::mzText('secret', 'Secret Token') }}
                                </div>
                                <div class='row'>
                                    {{ Form::mzText('pre_hook', 'Pre Hook Script') }}
                                </div>
                                <div class='row'>
                                    {{ Form::mzText('post_hook', 'Post Hook Script') }}
                                </div>

                                <center>
                                    <div class='row'>
                                        {!! Form::button($isEdit ? "SUBMIT" : "CREATE", ['class' => 'col s12 btn btn-large waves-effect indigo', 'type' => 'submit']) !!}
                                    </div>
                                </center>
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </center>

    </main>
@endsection

@push('js')
    <script>
        $(document).ready(function() {
            $('select').material_select();
            $(".toastMessage").each(function(index) {
                Materialize.toast($(this).data('content'), 4000, 'red')
            });
        });
    </script>
@endpush

resources/views/projects/index.blade.php
@extends('layouts.dashboard')

@section('main-content')
@if ($errors->any())
    @foreach ($errors->all() as $error)
        <div class="hidden toastMessage" data-content="{{ $error }}"></div>
    @endforeach
@endif

<div class="container main-content">
    <div class="row">
        <div class="col s12">
            <div style="float:right; margin-bottom: 20px;">
                <a href="{{ route('projects.create') }}" title="Create Project" class="btn indigo darken-2 waves-effect waves-light"><i class="material-icons right">add_circle_outline</i> Create</a>
            </div>
            <table class="bordered">
                <thead>
                    <tr>
                         <th width="30%">Name</th>
                         <th width="40%">Last Log</th>
                         <th width="10%">Status</th>
                         <th width="10%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($projects as $project)
                        <tr>
                            <td>{{ $project->name }}</td>
                            @if (isset($project->last_log))
                                <td>{!! "<b>" . $project->last_log->updated_at . "</b> - " . $project->last_log->content !!}</td>
                            @else
                                <td>Nothing to show here</td>
                            @endif
                            <td>{{ $project->status_name }}</td>
                            <td><a href="{{ route('projects.show', $project->id) }}" class="btn red waves-effect waves-light"><i class="material-icons left" style="margin:0">info_outline</i></a></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

@push('js')
    <script>
        $(document).ready(function() {
            $(".toastMessage").each(function(index) {
                Materialize.toast($(this).data('content'), 4000, 'red')
            });
        });
    </script>
@endpush

resources/views/projects/show.blade.php
@extends('layouts.dashboard')

@push('css')
<style>
    body {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
    }

    main {
        flex: 1 0 auto;
    }

    body {
        background: #fff;
    }

    .input-field input[type=date]:focus + label,
    .input-field input[type=text]:focus + label,
    .input-field input[type=email]:focus + label,
    .input-field input[type=password]:focus + label {
        color: #e91e63;
    }

    .input-field input[type=date]:focus,
    .input-field input[type=text]:focus,
    .input-field input[type=email]:focus,
    .input-field input[type=password]:focus {
        border-bottom: 2px solid #e91e63;
        box-shadow: none;
    }
    input:-webkit-autofill {
        -webkit-box-shadow: 0 0 0 30px #fafafa  inset !important;
    }
</style>
@endpush

@section('main-content')
<body style="background-color: #eee">
    @if ($errors->any())
        @foreach ($errors->all() as $error)
            <div class="hidden toastMessage" data-content="{{ $error }}"></div>
        @endforeach
    @endif
    <div class="section"></div>
    <main>
        <center>
            <div class="section">
                <h4>{{ $project->name }} <a href="{{ route('projects.edit', $project->id) }}" class="btn waves-effect waves-light red" style="padding:0 10px"><i class="material-icons" style="margin:0">edit</i></a></h4>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <div class="col s12 m6 l6">
                        <div class="z-depth-1 grey lighten-5 row" style="padding: 32px 48px 32px 48px;">
                            <div class="row">
                                <div class="col s12">
                                    <h5 class="left-align">Details</h5>
                                </div>
                            </div>
                            <div class='row'>
                                {{ Form::mzText('name', 'Project Name', $project->name, ['disabled']) }}
                            </div>
                            <div class='row'>
                                {{ Form::mzText('branch', 'Branch', $project->branch, ['disabled']) }}
                            </div>
                            <div class='row'>
                                {{ Form::mzText('path', 'Path', $project->path, ['disabled']) }}
                            </div>
                            <div class='row'>
                                {{ Form::mzSelect('status', 'Status', ['0' => 'Inactive', '1' => 'Active'], $project->status, ['disabled']) }}
                            </div>
                            <div class='row'>
                                {{ Form::mzText('secret', 'Secret Token', $project->secret, ['disabled']) }}
                            </div>
                            <div class='row'>
                                {{ Form::mzText('pre_hook', 'Pre Hook Script', $project->pre_hook, ['disabled']) }}
                            </div>
                            <div class='row'>
                                {{ Form::mzText('post_hook', 'Post Hook Script', $project->post_hook, ['disabled']) }}
                            </div>
                        </div>
                    </div>
                    <div class="col s12 m6 l6">
                        <div class="z-depth-1 grey lighten-5 row" style="padding: 32px 48px 32px 48px;">
                            <div class="row">
                                <div class="col s12">
                                    <h5 class="left-align">Logs</h5>
                                </div>
                            </div>
                            <table class="bordered">
                                <thead>
                                    <tr>
                                        <th width="30%">Time</th>
                                        <th>Content</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($project->logs as $log)
                                    <tr>
                                        {{-- <div class="row"> --}}
                                            {{-- <div class="col s12"><b></div> --}}
                                        <td><b>{{ $log->created_at }}</b></td>
                                        <td> {!! $log->content !!}</td>
                                        {{-- </div> --}}
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </center>

    </main>
@endsection

@push('js')
    <script>
        $(document).ready(function() {
            $('select').material_select();
            $(".toastMessage").each(function(index) {
                Materialize.toast($(this).data('content'), 4000, 'red')
            });
        });
    </script>
@endpush